_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 64
episodes:
    value: 5
epsilon:
    value: 1
epsilon_decay:
    value: 0.995
epsilon_min:
    value: 0.1
gamma:
    value: 0.99
learning_rate:
    value: 0.001
max_steps:
    value: 200
memory_size:
    value: 10000
target_model_update_freq:
    value: 5
