_wandb:
    value:
        cli_version: 0.19.11
        code_path: code/main.py
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 2
                - 3
                - 55
            "2":
                - 2
                - 3
                - 55
            "3":
                - 13
                - 15
                - 16
                - 17
                - 23
                - 55
                - 61
            "4": 3.11.9
            "5": 0.19.11
            "8":
                - 3
                - 5
            "10":
                - 3
            "12": 0.19.11
            "13": windows-amd64
environment:
    value:
        data_dir: ./data
        mode: training
        variant: 0
model:
    value:
        device: cpu
        network: mlp
        network_type: Sequential
        prioritized_replay: true
        target_update_freq: 5
training:
    value:
        batch_size: 64
        buffer_size: 10000
        episodes: 20
        epsilon_decay: 0.995
        epsilon_min: 0.1
        epsilon_start: 1
        gamma: 0.99
        learning_rate: 0.001
        seed: 42
