_wandb:
    value:
        cli_version: 0.21.0
        code_path: code/main_ppo.py
        e:
            zdeqsyk0o3ty4wyx32hlleiik52oi9pc:
                args:
                    - --seed
                    - "25"
                codePath: main_ppo.py
                codePathLocal: main_ppo.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1081101176832"
                        used: "17703337984"
                email: battist.becker@web.de
                executable: /home/battist/miniconda3/envs/lab/bin/python
                git:
                    commit: ee409f68b96ad4c02c30c9751cd046404812cec1
                    remote: https://github.com/fivecodingfive/ducks-riding-lamas
                gpu: NVIDIA GeForce RTX 4050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      memoryTotal: "6439305216"
                      name: NVIDIA GeForce RTX 4050 Laptop GPU
                      uuid: GPU-f9ac9efa-30db-a625-7ab2-551748806900
                host: Battist-Laptop
                memory:
                    total: "8235892736"
                os: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/battist/projects/ducks-riding-lamas/main_ppo.py
                python: CPython 3.11.9
                root: ./wandb
                startedAt: "2025-07-04T08:16:43.101773Z"
                writerId: zdeqsyk0o3ty4wyx32hlleiik52oi9pc
        m:
            - "1": episode
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.9
        t:
            "1":
                - 2
                - 3
            "2":
                - 2
                - 3
            "3":
                - 7
                - 13
                - 15
                - 16
                - 61
            "4": 3.11.9
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
device:
    value: gpu
env_variant:
    value: 0
ppo_config:
    value:
        action_size: 5
        clip_ratio: 0.1
        entropy: 0.1
        entropy_decay: 0.96
        entropy_min: 0
        gamma: 0.999
        lam: 0.925
        max_time_steps: 200
        n_episodes: 200
        policy_learning_rate: 0.0003
        state_size: 10
        train_policy_epochs: 5
        train_value_function_epochs: 5
        value_learning_rate: 0.0005
seed:
    value: 25
sweep_id:
    value: null
